sudo: true

cache:
  directories:
    - node_modules
    - vendor
    - yarn

before_install:
  - sudo addgroup --gid 1000 nginx
  - sudo useradd --uid 1000 -g nginx nginx
  - cp .env.testing .env

install:
  - sudo service postgresql stop
  - rm -rf /var/lib/postgresql/data
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php make install
  - mkdir public/uploads
  - sudo chown -R nginx:nginx $TRAVIS_BUILD_DIR

before_script:
  - docker-compose exec --user=nginx:nginx php php vendor/bin/codecept build
  - docker-compose exec --user=nginx:nginx php php artisan config:clear
  - docker-compose exec --user=nginx:nginx php php artisan route:clear

script:
  - docker-compose exec --user=nginx:nginx php php vendor/bin/codecept run
  - docker-compose exec --user=nginx:nginx php php vendor/bin/phpunit
  - docker-compose exec --user=nginx:nginx php php artisan dusk

after_script:
  - docker-compose stop
  - docker-compose rm -f
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
  - cat $TRAVIS_BUILD_DIR/tests/_output/*.html
  - cat $TRAVIS_BUILD_DIR/tests/Browser/console/*.*

#after_success:
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#  - docker build -f docker/coyote/Dockerfile -t 4programmers/coyote:latest .
#  - docker push 4programmers/coyote:latest
