services:
  php:
    environment:
      STRIPE_KEY: $STRIPE_KEY
      STRIPE_SECRET: $STRIPE_SECRET
      STRIPE_ENDPOINT_SECRET: $STRIPE_ENDPOINT_SECRET
      GOOGLE_MAPS_KEY: $GOOGLE_MAPS_KEY

  db:
    ports:
      - 5432:5432
