version: '3.5'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: coyote
      POSTGRES_PASSWORD:
      POSTGRES_DB: coyote
    networks:
      - coyote

  php:
    image: 4programmers/php-node:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - coyote

  cron:
    image: 4programmers/coyote:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: crond -f -l 8
    networks:
      - coyote

  nginx:
    image: nginx:1.17
    ports:
      - 8880:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - coyote

  redis:
    image: redis:5
    command: redis-server --appendonly no --save
    networks:
      - coyote

  elasticsearch:
    image: elasticsearch:5.6.14
    ports:
      - 9200:9200
    volumes:
        - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - coyote

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
    networks:
      - coyote

  graylog:
    image: graylog/graylog:3.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:29000/
    networks:
      - coyote
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 29000:9000
      - 12201:12201
      - 12201:12201/udp

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - 39000:9000
    networks:
      - coyote

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - coyote

  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    depends_on:
      - nginx
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - coyote

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minio minio123 --api s3v4;
      /usr/bin/mc mb minio/public;
      /usr/bin/mc mb minio/local;
      /usr/bin/mc policy set public minio/public;
      exit 0;
      "
    networks:
      - coyote

volumes:
  postgres:
  elasticsearch:
  minio:
  mongo:
  graylog:

networks:
  coyote:
    name: coyote

