name: Staging

on:
  push:
    branches:
    - staging

jobs:
  staging:
    runs-on: ubuntu-latest

    concurrency:
      group: staging
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGGING_IP }}
          username: github
          key: ${{ secrets.STAGGING_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/4programmers.dev
            git fetch
            git reset origin/staging --hard
            docker compose exec -T php composer install --no-dev
            docker compose exec -T php php artisan migrate --force
            docker compose exec -T php php artisan config:cache
            docker compose exec -T php php artisan route:cache
            docker compose exec -T php php artisan queue:restart
            docker compose exec -T php yarn install
            docker compose exec -T php yarn run prod
