name: Tests

on:
  pull_request:
    types: [ opened ]
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    concurrency:
      group: tests
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup config
        run: cp .env.default .env

      - name: Run docker containers
        run: docker compose -f docker-compose.yaml -f docker-compose.testing.yaml up -d
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/composer.lock') }}

      - name: Cache node dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup owner
        run: sudo chown -R runneradmin:runneradmin ./

      - name: Install packages
        run: make install

      - name: Run unit and legacy tests
        run: docker compose exec -T -u nginx php php vendor/bin/phpunit --testsuite Unit,Legacy

      - name: Run acceptance tests
        run: docker compose exec -T -u nginx php php vendor/bin/phpunit --testsuite Acceptance

      - name: Run look&feel tests
        run: docker compose exec -T -u nginx php php vendor/bin/phpunit --testsuite LookAndFeel

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: failed-acceptance-tests
          path: tests/Acceptance/*.FAIL.png
          if-no-files-found: ignore
